### ISSUE TITLE
RAM above code / Ibuff above EhBASIC patch issue with STR$

### ISSUE THREAD

**Issue by mgcaret** [Klaus2m5/6502_EhBASIC_V2.22#2]
When the RAM above code/Ibuff above EhBASIC patch is in place, the following output was occurring for me:

    Ready
    PRINT STR$(1)+STR$(2)+STR$(3)
     3 3 3

This is due to STR$'s conversion going onto the zero page.

    A$=STR$(1):B$=STR$(2):C$=STR$(3)
    PRINT SADD(A$);SADD(B$);SADD(C$)
     240 240 240

The issue can be fixed by adjusting the patch:

    ; *** begin RAM above code / Ibuff above EhBASIC patch ***
    ; *** replace
    ;      CMP   #>Ram_base        ; compare with start of program memory
    ;      BCS   LAB_RTST          ; branch if not in utility area
    ; *** with
          BEQ LAB_MVST        ; may be on zero page if LAB_296E was used, as in STR$
          CMP   #>Ibuffs          ; compare with location of input buffer page
          BNE   LAB_RTST          ; branch if not in utility area
    LAB_MVST
    ; *** end   RAM above code / Ibuff above EhBASIC patch ***

**Comment by Klaus2m5** [comment]
Thank you for the well documented problem and fix. I have updated the patch accordingly.
