### ISSUE TITLE
error compiling patched version of EhBasic

### ISSUE THREAD

**Issue by Java6502** [Klaus2m5/6502_EhBASIC_V2.22#4]
Sir,
I was wondering what compiler you are using for the patched version of EhBasic.  I am using the CC65 (CL65) toolchain.  I get errors with some of the syntax.  Particularly 

LN 1551 .IF [* & $FF] = $FD

LN 1630 CMP   #[TK_TAB-$80]*2

LN 3105 .IF [* & $FF] = $FD

LN 3342 CPX   #<[LAB_224Da+2]

and lastly

LN 3344 CMP   #>[LAB_224Da+2]

I'm guessing this is not valid syntax for CL65.  Any help would be appreciated.
Thanks,
Jonathan

**Comment by Klaus2m5** [comment]
The assembler I used is integrated into the Kowalski simulator. You can 
find an updated copy here: https://sbc.rictor.org/kowalski.html

My best guess is, that you need to replace the square brackets with 
round brackets to be able to assemble EhBASIC in CC65.

Am 09.09.2021 um 00:00 schrieb Java6502:

**Comment by Java6502** [comment]
Sir,
Thank you very much.  That did solve the issue.  So the patched EhBASIC successfully compiled with CC65, and is running on my SBC.  Thanks so much!
Jonathan
